# .github/workflows/deployment-status.yml
name: Deployment Status Trigger

on:
  deployment_status:
    types: [success]

jobs:
  post-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Post-Deployment Tasks
        run: |
          echo "The deployment was successful."
          echo "Performing post-deployment tasks for environment: ${{ github.event.deployment_status.environment }}"
          echo "Deployment description: ${{ github.event.deployment_status.description }}"
